# Travis Continuous Integration Configuration File, based on ..
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  - ROS_DISTRO=hydro WSTOOL=wstool
  - ROS_DISTRO=groovy WSTOOL=wstool
#notifications:
#  email:
#    recipients:
#      - roseus@jsk.t.u-tokyo.ac.jp
#    on_success: always #[always|never|change] # default: change
#    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - ./travis/before_install.sh
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - ./travis/install.sh
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - ./travis/script.sh
after_failure:
  - if [ -e ./build/Testing/Temporary/LastTest.log ]; then cat ./build/Testing/Temporary/LastTest.log; fi
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done

